In [2]:
import pandas as pd

In [4]:
heart_df = pd.read_csv('combinedHeartData.csv')
heart_df

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,52,1,2,106,200,1,0,161,1,3.9,0,3,3,high_chance
1496,50,1,3,77,297,1,3,184,0,0.3,1,2,1,high_chance
1497,49,1,2,160,269,0,0,198,1,5.9,2,0,3,low_chance
1498,49,1,0,114,195,0,0,172,0,5.5,2,1,1,high_chance
1499,56,1,0,113,188,0,1,140,1,4.3,1,0,2,low_chance

In [5]:
heart_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1500 non-null   int64
 1   sex       1500 non-null   int64
 2   cp        1500 non-null   int64
 3   trtbps    1500 non-null   int64
 4   chol      1500 non-null   int64
 5   fbs       1500 non-null   int64
 6   restecg   1500 non-null   int64
 7   thalachh  1500 non-null   int64
 8   exng      1500 non-null   int64
 9   oldpeak   1500 non-null   float64
 10  slp       1500 non-null   int64
 11  caa       1500 non-null   int64
 12  thall     1500 non-null   int64
 13  output    1500 non-null   object
dtypes: float64(1), int64(12), object(1)
memory usage: 164.2+ KB

In [7]:
!pip3 install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Collecting scikit-learn
  Downloading scikit_learn-1.2.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 215.6 kB/s eta 0:00:0000:0100:02
Requirement already satisfied: numpy>=1.17.3 in /home/raedin/.local/lib/python3.10/site-packages (from scikit-learn) (1.24.2)
Collecting threadpoolctl>=2.0.0
  Downloading threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Collecting joblib>=1.1.1
  Downloading joblib-1.2.0-py3-none-any.whl (297 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 298.0/298.0 KB 343.2 kB/s eta 0:00:0000:0100:01
Collecting scipy>=1.3.2
  Downloading scipy-1.10.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.4/34.4 MB 226.3 kB/s eta 0:00:0000:0100:04
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
Successfully installed joblib-1.2.0 scikit-learn-1.2.2 scipy-1.10.1 threadpoolctl-3.1.0

In [19]:
# PCA for feature extraction
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score, recall_score, confusion_matrix, precision_score

# Split data into train and test sets
X = heart_df.drop('output', axis=1)
y = heart_df['output']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print(X_train.head())

# Apply PCA to the data
pca = PCA(n_components=6)
pca.fit(X_train)

# Transform both the training set and the test set
X_train_pca = pca.transform(X_train)
X_test_pca = pca.transform(X_test)
print(X_train_pca.head())

# Create a random forest classifier
rfc = RandomForestClassifier()
rfc.fit(X_train_pca, y_train)

# Evaluate the model
accuracy = rfc.score(X_test_pca, y_test)
print('Accuracy: ', accuracy)
# accuracy = accuracy_score(X_test_pca, y_test)
# print('Accuracy: ', accuracy)

# f1 = f1_score(X_test_pca, y_test)
# print('F1 score: ', f1)

# recall_score = recall_score(X_test_pca, y_test)
# print('Recall score: ', recall_score)

# precision_score = precision_score(X_test_pca, y_test)
# print('Precision score: ', precision_score)

# confusion_matrix = confusion_matrix(X_test_pca, y_test)
# print('Confusion matrix: ', confusion_matrix)

      age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
118    46    0   1     105   204    0        1       172     0      0.0    2
21     44    1   2     130   233    0        1       179     1      0.4    2
1278   73    0   2     124   611    0        0       189     0      0.3    1
916    62    1   2     111   236    1        1       161     1      0.4    2
647    67    1   0     103   367    1        1       183     0      2.5    2

      caa  thall
118     0      2
21      0      2
1278    2      3
916     0      2
647     4      3

AttributeError: 'numpy.ndarray' object has no attribute 'head'